language: generic 

sudo: required
services:
- docker

before_install:
- docker build -t asiorgad/docker-react/frontend -f Dockerfile.dev .

script:
- docker run -e CI=true asiorgad/docker-react npm run test