language: generic 

sudo: required
services:
- docker

before_install:
- docker build -t asiorgad/docker-react -f Dockerfile.dev .

script:
- docker run  asiorgad/docker-react npm run test npm run test -- --coverage